openapi: 3.0.3
info:
  title: Producentens API för avisering - Hämtning av prenumerationsinformation
  description:
    En beskrivning av API:et som en producent behöver sätta upp för att erbjuda aviseringsfunktionalitet i samarbete med Min ärendens vidareförmedlingstjänst
    Denna fil innehåller beskrivningar av endpoints för hämtning av prenumerationsinformation
  version: 1.0
paths:
  /kundhandelser-prenumerationer/detaljer:
    post:
      summary: Hämta detaljer för en prenumeration
      description: Anropas från vidareförmedlingstjänsten när den eller en konsument vill hämta detaljer för en prenumeration
      parameters:
        - $ref: '../common/parameters.yaml#/components/parameters/requestId'
        - $ref: '../common/parameters.yaml#/components/parameters/correlationId'
      requestBody:
      responses:
        "200":
        "404":
        "403":

  
