openapi: 3.0.3
info:
  title: Vidareförmedlingstjänstens API mot konsumenter för avisering - Hantering av prenumerationer
  description:
    En beskrivning av API:et som Mina ärendens vidareförmedlingstjänst sätter upp mot konsumenter så att de kan hantera sina prenumerationer
  version: 1.0
paths:
  /kundhandelser-prenumerationer/upplagg:
    post:
      summary: Lägg upp prenumeration
      description: Anropas av konsumenttjänsten när den vill lägga upp en prenumeration på kundhändelser
      parameters:
        - $ref: '../../common/parameters.yaml#/components/parameters/clientId'
        - $ref: '../../common/parameters.yaml#/components/parameters/requestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/upplaggRequestSchema'
      responses:
        "200":
          description:
            Prenumerationen upplagd.
            Observera att det kan vara så att användaren/konsumenttjänsten inte var behörig på någonting av det man begärde att prenumerera på. Detta faktum indikeras i svaret men det blir ändå ett 200-svar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/upplaggResponseSchema'
        "400":
          description:
            Skickas till exempel när man vill ändra till ett historiskt slutdatum
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
        "501":
          description:
            En producent stödjer inte efterfrågad funktionslitet.
            Det kan t ex röra sig om anrop med taggar, juridiskt läsombud eller att identifiera part med ärende
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
  /kundhandelser-prenumerationer/borttag:
    post:
      summary: Ta bort en prenumeration
      description: Anropas av konsumenttjänsten när den vill ta bort en prenumeration på kundhändelser
      parameters:
        - $ref: '../../common/parameters.yaml#/components/parameters/clientId'
        - $ref: '../../common/parameters.yaml#/components/parameters/requestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/borttagRequestSchema'
      responses:
        "200":
          description: Prenumerationen borttagen
        "403":
          description: Skickas när prenumerationen tillhör en annan användare eller konsumenttjänst
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
        "404":
          description: Skickas till exempel när totalPrenumerationsID inte finns
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
  /kundhandelser-prenumerationer/andra:
    post:
      summary: Ändra en prenumeration
      description: Anropas av konsumenttjänsten när den vill ändra en prenumeration på kundhändelser
      parameters:
        - $ref: '../../common/parameters.yaml#/components/parameters/clientId'
        - $ref: '../../common/parameters.yaml#/components/parameters/requestId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/andraRequestSchema'
      responses:
        "200":
          description: Ändringen genomförd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/andraResponseSchema'
        "404":
          description: Skickas till exempel när totalPrenumerationsID inte finns eller om konsumenten försöker ta bort en kundhändelsetyp eller tag som inte ingår i prenumerationen
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
        "403":
          description: Skickas när prenumerationen tillhör en annan användare eller konsumenttjänst
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
        "400":
          description: Skickas till exempel när man försöker ändra till ett historiskt slutdatum
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
        "501":
          description:
            Producenten stödjer inte efterfrågad funktionalitet. (ändring av taggar)
          content:
            application/problem+json:
              schema:
                $ref: '../../common/schemas.yaml#/components/schemas/error'
components:
  schemas:
    upplaggRequestSchema:
      type: object
      properties:
        part:
          $ref: '../../common/schemas.yaml#/components/schemas/part'
        kundhandelseTyper:
          $ref: '../../common/schemas.yaml#/components/schemas/kundhandelseTyper'
        taggar:
          $ref: '../../common/schemas.yaml#/components/schemas/taggar'
        anvandare:
          $ref: '../../common/schemas.yaml#/components/schemas/anvandare'
        onskatSlutdatum:
          description:
            Önskat slutdatum.
            Om konsumenttjänsten anger ett datum som är längre bort än ett år framåt i tiden så kommer vidareförmedlingstjänsten att sätta om datumet till ett år framåt i tiden
          type: string
          format: date
        onskadAviseringstyp:
          $ref: '../../common/schemas.yaml#/components/schemas/onskadAviseringsTyp'
        auktorisationsMetod:
          $ref: '../../common/schemas.yaml#/components/schemas/auktoristionsMetod'
      required:
        - part
        - onskatSlutdatum
        - onskadAviseringstyp
    upplaggResponseSchema:
      type: object
      properties:
        totalPrenumerationsID:
          $ref: '../../common/schemas.yaml#/components/schemas/totalPrenumerationsID'
        totalStatus:
          description:
            Visar hur det gick med upplägget av prenumerationen.
            Tre möjliga värden
            OK - Det gick bra hos alla producenter och användaren/konsumenttjänsten var auktoriserad på alla kundhänelsetyper
            PARTIELL - Det gick bra hos några producenter och kundhändelesetyper men inte alla som var begärda
            TOM - Det gick inte bra hos någon producent/kundhändelsetyp
          type: string
          enum:
            - OK
            - PARTIELL
            - TOM
        faktisktSlutdatum:
          description:
            Slutdatum som det faktiskt blev i prenumerationen
          type: string
          format: date
        producenter:
          description: Lista med producenter som blev tillfrågade och deras status
          type: array
          items:
            type: object
            properties:
              producent:
                type: string
                description: producentens namn
              httpStatus:
                type: integer
                description: HTTP-koden som kom från producenten
              producentPrenumerationsID:
                $ref: '../../common/schemas.yaml#/components/schemas/producentPrenumerationsID'
              producentMessage:
                type: string
                description: Eventuellt felmedelande från producenten
              vftMessage:
                type: string
                description: Eventuellt felmeddelande från vidareförmedlingstjänsten
            required:
              - producent
              - httpStatus
              - producentPrenumerationsID
        kundhandelseTypsInformation:
          description:
            En lista med information om hur det gick med efterfrågade kundhändelsetyper
            Svaret innehåller information om vilka kundhändelsetyper på lövnivå man har fått prenumeration på samt hur många kundhändelsetyper på lövnivå man inte är auktoriserad för
            Om producenten svarade med ett felsvar är denna lista tom
          type: array
          items:
            type: object
            properties:
              begardKundhandelseTyp:
                type: string
                description: Vad begärdes (med eventuell wildcard)
              producent:
                type: string
                description: Producentens namn
              kundhandelseTyper:
                type: array
                description: Auktoriserade kundhändelsetypers (på lövenivå) identifierade
                items:
                  type: string
              antalIckeAuktoriserade:
                type: integer
                description: Hur många kundhändelsetyper för denna begärda kundhändelsetyp (och producent) var användaren/konsumenttjänsten inte auktoriserad på
            required:
              - begardKundhandelseTyp
              - producent
              - antalIckeAuktoriserade
      required:
        - totalStatus
        - faktisktSlutdatum
    borttagRequestSchema:
    andraRequestSchema:
    andraResponseSchema:
  
